[package]
name = "libplamo"
version = "0.1.0"
authors = ["Shogo Otake <shogo.otake@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "plamo"
crate-type = ["cdylib"]

[dependencies]

[profile.release]
lto = true
